const model = {
    app: {
        apiKey: '',
        language: 'no, eng',
        currentPage: 'mainLibrary',
        searchedBook: null,
        selectedBook: null,
        scrollIndex: 0,
        Page: [
            {id: 'mainPage'},
            {id: 'mainLibrary'},
            {id: 'mainBrowse'},
            {id: 'currentLibrary'},
            {id: 'tbrLibrary'},
            {id: 'finishedLibrary'},
            {id: ''},
            {id: ''},
            {id: ''},
            {id: ''},
        ]
    },
    inputs: {
        searchBarBrowser: null,
        searchBarLibrary: null,

    },
    data:{
        bookData: { 
            id: '',
            series: '',
            author: '',
            releaseYear: null,
            cover: '',
            categories: [],
        },
        categories: ['Fiction','Fantasy','Romance','Dark','Crime','Historical',
                    'Young Adult','Dystopian','Thriller','Mystery','Nonfiction',
                    'Psycology','Philosophy','Self help','Autobiography','Biography',
                    'Science Fiction','Poetry','Politics','Education','Health','Music',
                    'Classic','Travel','Religion',],
        Books: [
            {
                id: 1,
                name: 'The Crimson Moth',
                series: 'The Crimson Moth #1',
                author: 'Kristen Ciccarelli',
                releaseYear: 2024,
                cover: 'https://cdn.thestorygraph.com/qy2pzc17ahunidb7ew5eeupouegq',
                categories: [],
            },
            {
                id: 2,
                name: 'The Awakening',
                series: 'Zodiac Academy #1',
                author: 'Susanne Valenti, Caroline Packham',
                releaseYear: 2019,
                cover: 'https://cdn.thestorygraph.com/vjgvkuiwm2yste4zb8r9h4as306e',
                categories: [],
            },
            {
                id: 3,
                name: 'One Dark Window',
                series: 'The Sheperd King #1',
                author: 'Rachel Gillig',
                releaseYear: 2022,
                cover: 'https://cdn.thestorygraph.com/mktex5xwck3ubhro36dx1s4n7yg9',
                categories: [],
            },
            {
                id: 4,
                name: 'When the Moon Hatched',
                series: 'Moonfall #1',
                author: 'Sarah A. Parker',
                releaseYear: 2024,
                cover: 'https://cdn.thestorygraph.com/0r8a50lttroximz5f4toi5bu9r2h',
                categories: [],
            },
            {
                id: 5,
                name: 'Spark of the Everflame',
                series: "The Kindred's Curse",
                author: 'Penn Cole',
                releaseYear: 2023,
                cover: 'https://cdn.thestorygraph.com/clwjjmr1dse0fvmw55hpa1y5m75w',
                categories: [],
            },
            {
                id: 6,
                name: 'The Courage to be Disliked: How to free yourself, change yoru life and achieve real happiness',
                series: null,
                author: 'Fumitake Koga, Ichiro Kishimi with Adrian Mulraney',
                releaseYear: 2013,
                cover: 'https://cdn.thestorygraph.com/9jrgl3c0zfxq0jdpsceift0nyg2u',
                categories: [],
            },
            {
                id: 7,
                name: 'The Fellowship of the Ring',
                series: 'The Lord of the Rings #1',
                author: 'J.R.R. Tolkien',
                releaseYear: 1954,
                cover: 'https://cdn.thestorygraph.com/so691ptoyskgnadn3elj3525g3uv',
                categories: [],
            },
            {
                id: 8,
                name: 'Forth Wing',
                series: 'The Empytran #1',
                author: 'Rebecca Yarros',
                releaseYear: 2023,
                cover: 'https://cdn.thestorygraph.com/95moek15iljsn3q13lu92vpdq983',
                categories: [],
            },
            {
                id: 9,
                name: 'The Bone Witch',
                series: 'The Bone Witch #1',
                author: 'Rin Chupeco',
                releaseYear: 2017,
                cover: 'https://cdn.thestorygraph.com/ptz03fmhr2r7jgc7i4rgjynt01qi',
                categories: [],
            },
            {
                id: 10,
                name: 'a Fate inked in Blood',
                series: 'Saga of the Unfated #1',
                author: 'Danielle L.Jensen',
                releaseYear: 2024,
                cover: 'https://cdn.thestorygraph.com/v71zo3yg92woxf2y2l1rw1nu0e5q',
                categories: [],
            },
            {
                id: 11,
                name: 'Dragon Mage',
                series: 'Rivenworld #1',
                author: 'M.L. Spencer',
                releaseYear: 2020,
                cover: 'https://cdn.thestorygraph.com/o9nebceca47j8bqsouny5qot0t7c',
                categories: [],
            },
            {
                id: 12,
                name: 'Winter gods & Serpents',
                series: 'The Auran Chronicles #1',
                author: 'Wendy Heiss',
                releaseYear: 2021,
                cover: 'https://cdn.thestorygraph.com/m6ddiyx8mbfusnaure9hvj900z53',
                categories: [],
            },
            
            {
                id: 13,
                name: 'Six Crimson Cranes',
                series: 'Sig Crimson Cranes #1',
                author: 'Elizabeth Lim',
                releaseYear: 2021,
                cover: 'https://cdn.thestorygraph.com/0t5wn1w3jpj7t0b6wok398ltt10o',
                categories: [],
            },
            
            {
                id: 14,
                name: 'The return of the King',
                series: 'The Lord of the Rings #3',
                author: 'J.R.R. Tolkien',
                releaseYear: 1955,
                cover: 'https://cdn.thestorygraph.com/5hbmtu4xcyknlkwn2rqn2j8c7vjq',
                categories: [],
            },
            
        ],
        myLibrary: [
            1,2,3,4,5,6,7,8,9,10,11,12,13,14
        ],
        toBeReadList: [
            1,2,3,10,11,12,13,
        ],
        currentlyReadingList: [
            5,4,14
        ],
        finishedReading: [
            6,7,8,9
        ],
        searchedBookInfo: [
            4,3
        ],
    },
}